# version: '3.8'

services:
    pgdb:
        image: postgres:15
        container_name: postgres
        volumes:
            - ./ELK/postgres/tools/dump_logs.sh:/docker-entrypoint-initdb.d/dump_logs.sh
            - ./ELK/postgres/logs/:/var/log/postgresql/
            - postgres_data:/var/lib/postgresql/data/
        networks:
            - transcendance_net
            - elk_net
        restart: always
        env_file:
            - .env.example
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
            interval: 30s
            timeout: 10s
            retries: 5

    nginx:
        image: owasp/modsecurity-crs:nginx-alpine
        container_name: nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./srcs/nginx/tools/generate_certs.sh:/usr/local/bin/generate_certs.sh
            - ./srcs/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf:ro
            - ./srcs/nginx/modsecurity/modsecurity.conf:/etc/modsecurity.d/modsecurity.conf:ro
        command: "/bin/sh /usr/local/bin/generate_certs.sh"
        networks:
            - transcendance_net
        depends_on:
            - backend
            - frontend
    
    backend:
        image: django:trns
        container_name: backend
        build:
            context: ./srcs/api/
        volumes:
            - ./srcs/api/:/var/www/
        networks:
            - transcendance_net
            # - elk_net
        ports:
            - 8000:8000
        depends_on:
            - pgdb
        env_file:
            - .env.example
        restart: on-failure

    frontend:
        image: nextjs:trns
        build: ./srcs/frontend
        container_name: frontend
        ports:
            - "3000:3000"
        volumes:
            - ./srcs/frontend/src/:/app/src/
        depends_on:
            - backend
        networks:
            - transcendance_net
        restart: on-failure

volumes:
    postgres_data:

networks:
    transcendance_net:
        name: trans
    elk_net:
        external: true
        name: elk_net
