# version: '3.8'

services:
    pgdb:
        image: postgres:15
        container_name: postgres
        volumes:
            - ./ELK/postgres/tools/dump_logs.sh:/docker-entrypoint-initdb.d/dump_logs.sh
            - ./ELK/postgres/logs/:/var/log/postgresql/
            - postgres_data:/var/lib/postgresql/data/
        # entrypoint: ["/docker-entrypoint-initdb.d/dump_logs.sh"]
        networks:
            - transcendance_net
            - elk_net
        restart: always
        env_file:
            - .env.example


    backend:
        image: django:trns
        container_name: backend
        build:
            context: ./srcs/api/
        volumes:
            - ./srcs/api/:/var/www/
        networks:
            - transcendance_net
            # - elk_net
        ports:
            - 8000:8000
        depends_on:
            - pgdb
        env_file:
            - .env.example
        restart: on-failure
        # environment:
        #     DEBUG: True # ['True', 'False']
        #     DJANGO_SETTING_MODULE: config.django.local
        #     DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@pgdb:5432/${POSTGRES_DB}
        #     DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME}
        #     DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL}
        #     DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}

    frontend:
        build: ./srcs/frontend
        container_name: nextJs
        ports:
            - "3000:3000"  # Map host port 3000 to container port 3000
        volumes:
            - ./srcs/frontend/src/:/app/src/
        depends_on:
            - backend
        networks:
            - transcendance_net
        restart: on-failure

volumes:
    postgres_data:
    backend_files:
    #     driver: local
    #     driver_opts:
    #         type: none
    #         o: bind
    #         device: /Users/zel-bouz/transcendance/srcs/api

networks:
    transcendance_net:
    elk_net:
        external: true
        name: elk_net
